### ISSUE TITLE
It seems to work only in neovim

### ISSUE THREAD

**Issue by basilgood** [opalmay/vim-smoothie#1]
Throws an error in vim 9 even if I have:  ```let g:smoothie_hide_cursor = 0```
``` vim
Error detected while processing ~/.vim/plugged/vim-smoothie/autoload/smoothie.vim:
line    9:
E423: Illegal argument: blend=100
```
vim 9 (or vim) doesn't have ```highlight-blend```

**Comment by opalmay** [comment]
Should be fixed with latest commit, could you check?

**Comment by basilgood** [comment]
It works perfectly. Thanks you.
