### ISSUE TITLE
Center screen after scrolling 

### ISSUE THREAD

**Issue by MinmoTech** [opalmay/vim-smoothie#2]
I have described the issue on the original repo here: https://github.com/psliwka/vim-smoothie/issues/46 :slightly_smiling_face:

**Comment by opalmay** [comment]
Instead of using the native `zz` try putting it inside a `smoothie#do` as well

**Comment by opalmay** [comment]
Or `:set scrolloff=999`

**Comment by MinmoTech** [comment]
Thanks a lot!
